In [7]:
import numpy as np
>>> m_sqr_arr = np.array([[3, 7], [5, 2]])
>>> print(m_sqr_arr)
>>> np.linalg.svd(m_sqr_arr, full_matrices = True, compute_uv = True)

[[3 7]
 [5 2]]


(array([[-0.85065081, -0.52573111],
        [-0.52573111,  0.85065081]]),
 array([8.71337969, 3.32821489]),
 array([[-0.59455781, -0.80405286],
        [ 0.80405286, -0.59455781]]))

In [8]:
import numpy as np
>>> m_mx = np.matrix('0 1 3; 2 3 1; 0 1 0')
>>> print(m_mx)
>>> np.linalg.svd(m_mx)

[[0 1 3]
 [2 3 1]
 [0 1 0]]


(matrix([[-0.56667985,  0.82277903,  0.04368772],
         [-0.80674247, -0.54329657, -0.23236915],
         [-0.16745308, -0.16692366,  0.97164601]]),
 array([4.34019342, 2.41561763, 0.57228713]),
 matrix([[-0.37175416, -0.72677875, -0.5775738 ],
         [-0.44982001, -0.40322372,  0.79691442],
         [-0.81207192,  0.5560605 , -0.17701953]]))

In [9]:
import numpy as np
>>> m_mx_2 = np.matrix('5 7 6 4 2; 1 3 4 1 3; 3 4 5 4 1')
>>> print(m_mx_2)
>>> np.linalg.svd(m_mx_2)

[[5 7 6 4 2]
 [1 3 4 1 3]
 [3 4 5 4 1]]


(matrix([[-0.75927897,  0.23445293, -0.60706446],
         [-0.3639706 , -0.92629427,  0.09749016],
         [-0.53946348,  0.29497584,  0.78864974]]),
 array([14.94713352,  2.72739944,  1.46440832]),
 matrix([[-0.38661298, -0.57300074, -0.58264507, -0.37190679, -0.21073828],
         [ 0.41464331,  0.01546935, -0.3019654 ,  0.43683401, -0.73879941],
         [-0.39052151, -0.5479222 ,  0.47174175,  0.56256936, -0.09082761],
         [-0.43720626,  0.36725326, -0.53062765,  0.5481159 ,  0.30328039],
         [ 0.5787443 , -0.48614521, -0.2554127 ,  0.23226293,  0.55635974]]))

In [10]:
import numpy as np
>>> A = [[5, 7, 6],
         [4, 2, 1],
         [3, 4, 1],
         [3, 3, 4],
         [5, 4, 1]]
>>> print(A)
>>> np.linalg.svd(A)

[[5, 7, 6], [4, 2, 1], [3, 4, 1], [3, 3, 4], [5, 4, 1]]


(array([[-0.7027403 , -0.46685359, -0.21410908, -0.49155031, -0.02719193],
        [-0.28359468,  0.43753177,  0.58006323, -0.23058944, -0.58180339],
        [-0.33147393,  0.28537754, -0.61435714,  0.49436281, -0.43226775],
        [-0.38088944, -0.37286696,  0.49010103,  0.67827186,  0.12506689],
        [-0.41325343,  0.60839426,  0.00708838, -0.02755894,  0.67695516]]),
 array([14.71294705,  3.686851  ,  1.71356906]),
 array([[-0.60160874, -0.65302683, -0.46002487],
        [ 0.59545726,  0.01724365, -0.80320191],
        [ 0.53244491, -0.75713844,  0.37847564]]))